# Basic
title: I'm WRong 
subtitle: The meaning of life is that it stops. 
welcome_message: <a href="https://github.com/misswrongwrong/" target="_blank">Nothing</a>
description: AI, Programming, Reading, Gym and Beautiful things.
creator: <a href="http://misswrongwrong.github.io">@rong</a>

url: "https://misswrongwrong.github.io" 

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
#    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# latex
markdown: kramdown
mathjax: true

excerpt_separator: ""

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: misswrongwrong
    mail: misswrongwong(at)gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host



